config/routes.rb
Dinox::Application.routes.draw do

  
  resources :home do
  
     collection do
         get 'empresa'
         get 'produtos'
       end
     end
           
  resources :parceiro do
    collection do
      get 'new'
      post 'create_parceiro'
    end
  end
  
  resources :produto do
    get 'new'
  end
  
  
  root :to => 'home#index'
  
  
  

end

app/models/site/contact.rb
class Site::Contact < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :name, :email, :telefone, :message, :cidade, :estado, :cep, :rua, :numero, :bairro, :cpf_cnpj
  validates :name, :email, :cidade, :estado,  :presence=>true

  validates :telefone,
    :format => {:with => /^[(]{1}\d{2}[)]{1} {0,1}\d{8}$/}, :presence =>true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Site
  
  protect_from_forgery

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html, :js
  
  def index
  end
  
  def empresa   
  end
  
  def produtos    
  end

end

app/controllers/parceiro_controller.rb
#encoding: utf-8
class ParceiroController < ApplicationController
  
  respond_to :html, :js
    
  before_filter :initialize_contact  
  
  def initialize_contact
    @site_contact = Site::Contact.new
  end
 
  def create_parceiro
    begin
      @contact = Contact.new(params[:site_contact])
      if ParceiroMailer.new_parceiro(@contact).deliver
        flash[:notice] = 'Obrigado pelo seu contato!'
        redirect_to new_parceiro_path
      else
        redirect_to new_parceiro_path
      end
    rescue ScriptError
      flash[:error] = 'Desculpe-nos, não recebemos seu cadastro!'
    end
  end
  
end

app/controllers/produto_controller.rb
class ProdutoController < ApplicationController

  respond_to :html, :js 
  
  before_filter :initialize_produto
  
  def initialize_produto
    @produto = params[:param]
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empresa_helper.rb
module EmpresaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parceiro_helper.rb
module ParceiroHelper
end

app/helpers/produto_helper.rb
module ProdutoHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/home/_empresa.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">A empresa</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    <div id="conteudo_empresa">
      
      <%= image_tag 'Dinox_1.jpg' %>
      
      <p id="texto_empresa">
        Marcas que fazem História...<br><br>
        A Dinox Marcadores em Aço Inox é  uma empresa atuante no ramo de marcadores 
        para animais em aço inox, com uma tradição de mais de 50 anos passada de pai 
        para filho. A DINOX foi uma empresa que deu continuidade a este trabalho evoluindo 
        para o aço inox, mas mantendo a tradição e não perdendo a filosofia de sua 
        qualidade e satisfação de seus clientes.
      </p>     
      
    </div>
    
  </div>
</div>

app/views/home/_produtos.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Mochadores</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3>Importância de Mochar o Gado</h3>
    
    <p id="texto_produtos">
      Em todas as raças, existe uma tendência mundial na eliminação dos chifres 
      através do avanço das variedades mochas, não é a toa que muitos criadores 
      descornam seus bezerros, o mocho é mais dócil, o que facilita o manejo ganhando 
      peso mais rápido, tanto no pasto como no confinamento, e tem mais, o mocho cabe 
      em maior número no caminhão dando economia no transporte, cabe em maior quantidade
      no cocho economizando assim, construção e mão de obra.Veja abaixo alguns modelos de
      mochadores que a DINOX MARCADORES EM AÇO INOX disponibiliza para você. 
    </p>
    

    
  </div>
</div>

app/views/home/_pupup_comunicado_fraude.html.erb
<p>Prezados clientes,</br>

Assim como está ocorrendo com diversas empresas do País, boletos fraudulentos estão sendo enviados para nossos clientes na tentativa de iludir para um suposto pagamento com desconto, em substituição aos boletos verdadeiros encaminhados pela Dinox.

Eles alegam que houve erro no cálculo da alíquota do Pis/Cofins e encaminham, no anexo, um boleto falso com um desconto.

Trata-se de prática que, infelizmente, está atingindo um grande número de empresas e, por esta razão, comunicamos nossos clientes que, ao receberem email com este conteúdo, não efetuem qualquer pagamento e, em caso de dúvida, entre imediatamente em contato conosco.

A Dinox não se responsabilizará por qualquer pagamento que seja feito erroneamente.</br>

Att.</br>

Dinox</br>

(14) 3471-2545</br>
</p>
 
<p>
Texto do email:

Endereço do email fraudulento: cobrança@syscob0.com

Informamos a ................, que devido a problemas operacionais em nosso programa de faturamento de NFe, houve um erro no cálculo da alíquota PIS/Cofins, sendo que foi contabilizado a cobrança a mais do valor de R$ .....

Como forma de equalizar o erro de nosso programa, estaremos bonificando com um crédito de R$......... no título ........, com data de vencimento para .......

Solicitamos que despreze o boleto anterior (NÃO EFETUE O PAGAMENTO) de ...... (em DDA) e utilize o NOVO BOLETO EM ANEXO com valor corrigido de .............

Por gentileza, solicitamos que confirme o recebimento.

Obs.: Crédito/Bonificação referente a divergência na cobrança da alíquota PIS/Cofins/CSLL cobrado a maior.</br>

Patrícia Silva</br>

Dpto Financeiro</br>

DUMA ARTEFATOS DE FERRO E AÇO LTDA.</br>
</p>

app/views/home/empresa.js.erb
$("#yield-box").html('<%= escape_javascript(render(:partial => 'home/empresa'))%>');

app/views/home/index.html.erb
<div id="banner">
  
  <div class="center">
    
    <div id="slider">
      
      <ul class="rslides">
        <li><%= image_tag 'banner/index_banner_1.png', :alt=>"" %> 
          <p class="texto_banner_titulo texto_banner_color">JOGO DE NÚMEROS</p>
          <p class="texto_banner texto_banner_color">
            confeccionados em aço inox
          </p> 
          <div class="link_banner">
            <%= link_to 'veja mais', new_produto_path(:param => "jogonumero"), :remote => :true, :class => "link" %>
          </div>
        </li>
        
        <li><%= image_tag 'banner/index_banner_2.png', :alt=>"" %>
          <p class="texto_banner_titulo texto_banner_color">FOGAREIRO</p>
          <p class="texto_banner texto_banner_color">
            atualmente os melhores, mais econômicos  e mais práticos.
          </p>          
          <div class="link_banner">
            <%= link_to 'veja mais', new_produto_path(:param => "flambadores"), :remote => :true, :class => "link" %>
          </div>
        </li>
      </ul>
    
    </div>    
    
  </div>
</div>

<div class="conteudo">
  <div class="center">
    <div id="homeconteudo">
    
      <%= image_tag 'Dinox_1.jpg', :id => 'imghome' %>
      
      <h3>A Empresa</h3>
      
      <p id="texto_home">
        Marcas que fazem História...<br><br>
        A Dinox Marcadores em Aço Inox é  uma empresa atuante no ramo de marcadores 
        para animais em aço inox, com uma tradição de mais de 50 anos passada de pai 
        para filho. A DINOX foi uma empresa que deu continuidade a este trabalho evoluindo 
        para o aço inox, mas mantendo a tradição e não perdendo a filosofia de sua 
        qualidade e satisfação de seus clientes.
      </p>
    
    </div>
    
  </div>
</div>

app/views/home/produtos.js.erb
$("#yield-box").html('<%= escape_javascript(render(:partial => 'home/produtos'))%>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinox - Marcadores para animais em aço Dinox</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

</head>

<div id="caixa-comunicado">
	<div class="close"></div>
	<%= render :partial => "pupup_comunicado_fraude" %>
</div>
  
<div id="background_opacity"></div>

<body>  
  <header>
    <div class="center">
      
      <%= link_to(image_tag("logo.png", :id => 'imglogo'), root_path) %>      
      
      <nav>
        <ul id="menu">          

          <li id="li_contato" class="menu_li">
            <%= image_tag 'contato.png' %> <%= link_to 'Contato', new_site_contact_path, :remote => :true, :id => 'li_contato', :class => 'li_menu' %>
          </li>
                   
          <li id="li_parceiro" class="menu_li">
            <%= image_tag 'parceiro.png' %> <%= link_to 'Seja um parceiro', new_parceiro_path, :remote => :true, :id => 'li_parceiro', :class => 'li_menu' %>
          </li>

          <li id="li_produtos" class="menu_li">
            <%= image_tag 'produtos.png' %> <p id="li_produtos">Produtos</p>
          
            <span>
              <nav id="nav">
          
                <ul id="ul2">
                  <li class="menu_produtos">
                    <%= link_to '-Esporas', new_produto_path(:param => 'esporas'), :remote => :true, :id => 'li_produtos'%>
                  </li>

                  <li class="menu_produtos">
                    <%= link_to '-Tábua personalizada', new_produto_path(:param => "tabuas"), :remote => :true, :id => 'li_produtos'  %>
                  </li>

                  <li class="menu_produtos">
                     <%= link_to '-Freios', new_produto_path(:param => "freios"), :remote => :true, :id => 'li_produtos'  %>
                  </li>
                  
                </ul>

                <ul id="ul1">
                  <li class="menu_produtos">
                    <%= link_to '-Flambadores a gás', new_produto_path(:param => "flambadores"), :remote => :true, :id => 'li_produtos' %>
                  </li>

                  <li class="menu_produtos">
                    <%= link_to '-Mochadores', new_produto_path(:param => "mochadores"), :remote => :true, :id => 'li_produtos'  %>
                  </li>

                  <li class="menu_produtos">
                     <%= link_to '-Marcadores', new_produto_path(:param => "marcadores"), :remote => :true, :id => 'li_produtos'  %>
                  </li>
                  
                  <li class="menu_produtos">
                     <%= link_to '-Jogo de Números', new_produto_path(:param => "jogonumero"), :remote => :true, :id => 'li_produtos'  %>
                  </li>
                  
                </ul>

              </nav> 
            </span>
          </li>
          
          <li id="li_empresa" class="menu_li">
            <%= image_tag 'empresa.png' %> <%=  link_to 'A empresa',  empresa_home_index_path, :remote=> :true, :id => 'li_empresa', :class => 'li_menu'  %>              
          </li>

        </ul>
      </nav>
    </div>
    
  </header>
  
  <div id="yield-box">
    <%= yield %>
  </div>
  
  <footer>    
        
    <div class="center">
      <div id="rodape">

            <div class="itemrodape">
              <%= image_tag 'localizacao.png' %>
              <div class="txtrodape">
                <p1>Localização</p1>
                <p class="txt">
                  Rua Ary Rosário, 10 - Distrito Industrial 2 Garça - São Paulo - CEP: 17.400-000
                </p>
              </div>
            </div>
          
            <div class="itemrodape">
              <%= image_tag 'telefone.png' %>
              <div class="txtrodape">
                <p1>Telefone</p1>
                <p class="txt">
                  Fone: (14)3471-2545 <br> Fone/Fax: (14)3406-4636              
                </p>
              </div>
            </div>
          
            <div class="itemrodape2">
              <%= image_tag 'email.png' %>
              <div class="txtrodape2">
                <p1>E-mail</p1>
                <p class="txt">
                  dinox@dinoxmarcadores.com.br  
                </p>
              </div>
            </div>
        
        </div>
      
    </div>
    
    <div id="rodape2">
      <div class="center">
        <p>Todos os direitos reservados</p>
      </div>
    </div>
    
  </footer>  

</body>

</html>

app/views/parceiro/_form.html.erb
<div class="contact_form">
    <%= simple_form_for @site_contact, :url => create_parceiro_parceiro_index_path, :method => :post, :remote => :true do |f| %>
          <div class="box-dados">
            <%= f.input :name, :label=>"Nome:"%>
            <%= f.input :numero, :label=>"N:", :required=>true %>
            <%= f.input :rua, :label=>"Rua:", :required=>true %>
            <%= f.input :bairro, :label=>"Bairro:", :required=>true %>
            <%= f.input :estado, :label=>"Estado:" %>
            <%= f.input :cidade, :label=>"Cidade:" %>            
            <%= f.input :cep, :label=>"Cep:", :required=> true %>
            <%= f.input :telefone, :label=>"Fone:" %>
            <%= f.input :cpf_cnpj, :label=>"CPF/CNPJ:", :required=>true %>
            <%= f.input :email, :label=> "E-mail:" %>            
          </div>
          <div class="submit">
           <%= f.submit "Enviar", :id => 'enviar' %>
          </div>
    <% end %>
</div>

app/views/parceiro/_new.html.erb
<div class="div-carregamento-pagina"></div> 

<%= image_tag 'loadinfo.gif', :id => 'load' %>

<div class="titulo_paginas">
    <div class="center">
      <p class="txt_titulo_paginas">Parceiros</p>
    </div>
</div>

<div class="flash">
  <%= flash[:notice] %>
</div> 

<div class="conteudo_paginas">
  <div class="center">
    
    <div id="parceiro">
      <div id="contato">

        <p>Preencha os campos abaixo e seja um parceiro de negócios Dinox!</p>

        

        <%= image_tag 'sejaparceiro.png' %>

        <%= render :partial => '/parceiro/form' %>

      </div>
      
    </div>
    
  </div>
</div>

app/views/parceiro/new.js.erb
$("#yield-box").html('<%= escape_javascript(render(:partial => 'parceiro/new'))%>');
 
$('#load').hide();
$('.flash').hide();

$('#enviar').click(function() {  

  $(document).ajaxStart(function() {
      $('.div-carregamento-pagina').addClass('div-ajax-carregamento-pagina2');  
      $('#load').show();      
  });
  
  $(document).ajaxStop(function() {
      $('.div-carregamento-pagina').removeClass('div-ajax-carregamento-pagina2'); 
      $('#load').hide();
      $(".flash").show();
      $(".flash").fadeOut(10000);
  });
   
});

$('#li_parceiro a').click(function() {
      $(document).ajaxStart(function() {
      $('#load').hide();
      $('.div-carregamento-pagina').removeClass('div-ajax-carregamento-pagina2'); 
  });
  
  $(document).ajaxStop(function() {
    $(".flash").hide();
  });
});

app/views/produto/_esporas.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Esporas</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3>Abaixo temos modelos de esporas totalmente em aço inox.</h3>
    
    <p id="texto_produtos">
       
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>
          <p></p>
          <%= image_tag 'esporas/2.jpg' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'esporas/5.jpg' %>
        </li>
                        
      </ul>
    </nav>
    
        
  </div>
</div>

app/views/produto/_flambadores.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Flambador</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3>O que é um Flambador?</h3>
    
    <p id="texto_produtos">
       Flambador que em algumas regiões também é chamado de AQUECEDOR nada mais é do que um equipamento usado para aquecer os marcadores até que os mesmos estejam no ponto para "Tatuar" o couro do animal.  
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/10.jpg' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/11.jpg' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/12.JPG' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/1.jpg' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/img_1142.JPG' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/img_1152.JPG' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/img_1172.JPG' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/img_1182.JPG' %>
        </li>
        
        <li>
          <p></p>
          <%= image_tag 'flambadores/img_1273.JPG' %>
        </li>
                
        <li>
          <p></p>
          <% image_tag 'flambadores/img_1309.JPG' %>
        </li>
        
        <li>
          <p></p>
          <% image_tag 'flambadores/img_1315.JPG' %>
        </li>
      </ul>
    </nav>
    
        
  </div>
</div>

app/views/produto/_freios.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Freios</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3></h3>
    
    <p id="texto_produtos">
       
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>
          <p></p>
          <%= image_tag 'freios/22.jpg' %>
        </li>
                        
      </ul>
    </nav>
    
        
  </div>
</div>

app/views/produto/_jogonumero.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Jogo de Números</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">   
    
    <h3>Jogos de Números</h3>
    
    <p id="texto_produtos">
       Jogos de números confeccionados 100% em aço inox, classificados em dois modelos: 
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <%#*<li>%>
          <%#*<p></p>%>
          <%#= image_tag 'jogo_numeros/26.jpg', :class => 'ul_produtos img' %>
        <%#*</li>%>
        <li>
          <p></p>
          <%= image_tag 'jogo_numeros/img_1044.JPG', :class => 'ul_produtos img' %>
        </li>
        <li>
          <p></p>
          <%= image_tag 'jogo_numeros/img_1045.JPG', :class => 'ul_produtos img' %>
        </li>
        <li>
          <p></p>
          <%= image_tag 'jogo_numeros/img_1051.JPG', :class => 'ul_produtos img' %>
        </li>
        <li>
          <p></p>
          <%= image_tag 'jogo_numeros/img_1078.JPG', :class => 'ul_produtos img' %>
        </li>
           
      </ul>
    </nav>
    
    </div>
    
</div>

app/views/produto/_marcadores.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Marcadores</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3>Dinox marcadores em aço inox!</h3>
    
    <p id="texto_produtos">
       A DINOX MARCADORES EM AÇO INOX,  superou os problemas de marcação em animais bovinos e eqüinos. Encontramos a tecnologia adequada que nem mesmo a longo prazo sofrerá deformações. Logotipos fabricados em 100% aço inox, cabos de madeira tratada, garantem a precisão da marcação mantendo seu logotipo bem visualizado e dentro dos padrões originais, evitando dessa forma corte no couro do animal e um visual indesejado.
    </p>
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>
          <%= image_tag 'marcadores/7.jpg' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1580.JPG' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1587.JPG' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1594.JPG' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1655.JPG' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1677.JPG' %>
        </li>
        <li>
          <%= image_tag 'marcadores/img_1694.JPG' %>
        </li>
      </ul>
    </nav>

  </div>
</div>

app/views/produto/_mochadores.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Mochadores</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3>Importância de Mochar o Gado</h3>
    
    <p id="texto_produtos">
       Em todas as raças, existe uma tendência mundial na eliminação dos chifres através do avanço das variedades mochas, não é a toa que muitos criadores descornam seus bezerros, o mocho é mais dócil, o que facilita o manejo ganhando peso mais rápido, tanto no pasto como no confinamento, e tem mais, o mocho cabe em maior número no caminhão dando economia no transporte, cabe em maior quantidade no cocho economizando assim, construção e mão de obra.Veja abaixo alguns modelos de mochadores que a DINOX MARCADORES EM AÇO INOX disponibiliza para você. 
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>         
          <%= image_tag 'mochadores/6.jpg', :id => 'mochador02' %>
        </li>
        
        <li>
          <%= image_tag 'mochadores/23.jpg', :id => 'mochador03' %>
        </li>
        
        <li>
          <%= image_tag 'mochadores/img_0885.JPG', :id => 'mochador04' %>
        </li>
        
        <li>
          <%= image_tag 'mochadores/img_0947.JPG', :id => 'mochador05' %>
        </li>
        
        <li>
          <%= image_tag 'mochadores/img_0962.JPG', :id => 'mochador06' %>
        </li>
                        
      </ul>
    </nav> 
        
  </div>
  
</div>

app/views/produto/_new.html.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Produtos</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h1>Produtos</h1>
    

    
  </div>
</div>
    
  

app/views/produto/_tabuas.erb
<div class="titulo_paginas">
  <div class="center">
    <p class="txt_titulo_paginas">Tábua Personalizada</p>
  </div>
</div>

<div class="conteudo_paginas">
  <div class="center">
    
    <h3></h3>
    
    <p id="texto_produtos">
       
    </p>
    
    <nav id="nav_produtos">
      <ul id="ul_produtos">
        
        <li>
          <p></p>
          <%= image_tag 'tabuas/tabua_personalizada.jpg' %>
        </li>
                        
      </ul>
    </nav>
    
        
  </div>
</div>

app/views/produto/new.js.erb
$("#yield-box").html('<%= escape_javascript(render(:partial => 'produto/' + @produto))%>');

$('ul#menu li#li_produtos').addClass('selected');  

app/views/site/contacts/_form.html.erb
<div class="contact_form">
    <%= simple_form_for @site_contact, :remote => :true do |f| %>
          <div class="box-dados">
            <%= f.input :name, :label=>"Nome:"%>
            <%= f.input :estado, :label=>"Estado:" %>
            <%= f.input :cidade, :label=>"Cidade:" %>            
            <%= f.input :cep, :label=>"Cep:", :required=> true %>
            <%= f.input :telefone, :label=>"Fone:" %>
            <%= f.input :email,:label=> "E-mail:"  %>
                        
          </div>

          <div class="box-message">
            <%= f.input :message, :label=>"Menssagem: ", :as => :text, :required=> false %>
          </div>
          <div class="submit">
           <%= f.submit "Enviar", :id => 'enviar' %>
          </div>
    <% end %>
</div>

app/views/site/contacts/_new.html.erb
<div class="div-carregamento-pagina"></div> 

<%= image_tag 'loadinfo.gif', :id => 'load' %>

<div class="titulo_paginas">
    <div class="center">
      <p class="txt_titulo_paginas">Contato</p>
    </div>
</div>

<div class="flash"><%= flash[:notice] %></div>  

<div class="conteudo_paginas">
      
  <div class="center">
   
      <div id="contato">
    
        <p>Preencha os campos abaixo e seja um parceiro de negócios Dinox!</p>

        <%= image_tag 'contatoemail.png' %>
 
        <%= render :partial => '/site/contacts/form' %> 
      
      </div>
    
    <div id="localizacao">
      
      <p>Como chegar</p>
      
      <div id="mapa">
        
        <iframe width="955" height="280" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.br/maps?f=q&amp;source=s_q&amp;hl=pt-BR&amp;geocode=&amp;q=Rua+Ari+Ros%C3%A1rio,+Gar%C3%A7a,+S%C3%A3o+Paulo,+Brasil&amp;aq=&amp;sll=-22.212894,-49.679409&amp;sspn=0.003119,0.004978&amp;ie=UTF8&amp;t=m&amp;ll=-22.21355,-49.680283&amp;spn=0.002781,0.009967&amp;z=17&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.br/maps?f=q&amp;source=embed&amp;hl=pt-BR&amp;geocode=&amp;q=Rua+Ari+Ros%C3%A1rio,+Gar%C3%A7a,+S%C3%A3o+Paulo,+Brasil&amp;aq=&amp;sll=-22.212894,-49.679409&amp;sspn=0.003119,0.004978&amp;ie=UTF8&amp;t=m&amp;ll=-22.21355,-49.680283&amp;spn=0.002781,0.009967&amp;z=17" style="color:#0000FF;text-align:left">Exibir mapa ampliado</a></small>
        
      </div>
      
    </div>
      
  </div>
</div>
   

app/views/site/contacts/new.js.erb
$("#yield-box").html('<%= escape_javascript(render(:partial => 'site/contacts/new'))%>');

$('#load').hide();
$(".flash").hide(); 

$('#enviar').click(function() {  

  $(document).ajaxStart(function() {
      $('.div-carregamento-pagina').addClass('div-ajax-carregamento-pagina');  
      $('#load').show();
  });
  
  $(document).ajaxStop(function() {
      $('.div-carregamento-pagina').removeClass('div-ajax-carregamento-pagina'); 
      $('#load').hide();      
      $(".flash").show();
      $(".flash").fadeOut(10000);
  });
   
});

$('header nav ul li a').click(function() {
      $(document).ajaxStart(function() {
      $('#load').hide();
      $('.div-carregamento-pagina').removeClass('div-ajax-carregamento-pagina'); 
  });
  
  $(document).ajaxStop(function() {
    $(".flash").hide();
  });
});